# -*- coding: utf-8 -*-
"""
S00_femoral_joint_parameters.py

Shared configuration for the femoral-joint benchmark.

The benchmark combines a conventionally sliced mandrel with non-planar dome
layers. The CL-data generator, IK solvers, visualizer and G-code generator read
their shared settings from this file. Paths are relative to this file so the
benchmark folder can be moved without changing absolute paths.

Units:
- lengths: mm
- angles: radians unless the name ends in _DEG
- CL data: x y z i j k
- solved IK: x y z_table B C
"""

from __future__ import annotations

import os
import numpy as np


# ============================================================
# Benchmark files
# ============================================================

# Folder containing this parameter file.
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = THIS_DIR

# Cura input for the 3-axis mandrel/base.
INPUT_GCODE_FILENAME = "femoral_joint_mandrel_cura.gcode"
INPUT_GCODE_PATH = os.path.join(BASE_DIR, INPUT_GCODE_FILENAME)

# Intermediate CL-data generated by S01_femoral_joint_cldata_generator.py.
CURA_BASE_CLDATA_FILENAME = "01a_femoral_joint_mandrel_cldata.txt"
SPIRAL_CLDATA_FILENAME = "01b_femoral_joint_dome_cldata.txt"
SPIRAL_NO_EXTRUDE_INDICES_FILENAME = "01b_femoral_joint_dome_no_extrude_indices.txt"

CURA_BASE_CLDATA_PATH = os.path.join(BASE_DIR, CURA_BASE_CLDATA_FILENAME)
SPIRAL_CLDATA_PATH = os.path.join(BASE_DIR, SPIRAL_CLDATA_FILENAME)
SPIRAL_NO_EXTRUDE_INDICES_PATH = os.path.join(
    BASE_DIR,
    SPIRAL_NO_EXTRUDE_INDICES_FILENAME,
)

# Final combined CL data used by the IK solvers.
CLDATA_FILENAME = "01c_femoral_joint_combined_cldata.txt"
CLDATA_PATH = os.path.join(BASE_DIR, CLDATA_FILENAME)

# Global travel/no-extrusion row indices for the combined path.
COMBINED_NO_EXTRUDE_INDICES_FILENAME = "01c_femoral_joint_combined_no_extrude_indices.txt"
COMBINED_NO_EXTRUDE_INDICES_PATH = os.path.join(
    BASE_DIR,
    COMBINED_NO_EXTRUDE_INDICES_FILENAME,
)

# Solved IK output.
SOLVED_IK_FILENAME = "02_femoral_joint_solved_ik.txt"
SOLVED_IK_PATH = os.path.join(BASE_DIR, SOLVED_IK_FILENAME)


# ============================================================
# Coordinate conventions
# ============================================================

# CL X/Y coordinates are measured from the bed center.
XY_ORIGIN = "center"

# Positive z_table moves the bed downward in the world frame.
ZTABLE_POSITIVE_DOWN = True

# CL Z=0 refers to the bed top surface rather than the bed center.
CL_Z_ZERO_AT_BED_TOP = True


# ============================================================
# Machine envelope and frame geometry
# ============================================================

BASE_SIZE = np.array([500.0, 500.0, 30.0], dtype=float)
BED_SIZE = np.array([150.0, 150.0, 10.0], dtype=float)

Z_BASE_TOP = float(BASE_SIZE[2])
SPINDLE_HEIGHT = 500.0
GANTRY_Z = Z_BASE_TOP + SPINDLE_HEIGHT + 150.0

FRAME_X = 460.0
FRAME_Y = 460.0
POST_RADIUS = 12.0
BEAM_RADIUS = 10.0
SPINDLE_RADIUS = 20.0

CARRIAGE_SIZE = np.array([109.0, 100.0, 100.0], dtype=float)


# ============================================================
# Five-axis head geometry
# Must match both IK solvers and the visualizer.
# ============================================================

# B-axis pivot relative to the XY-carriage center.
B_PIVOT_FROM_CARRIAGE_CENTER = np.array([
    -26.0,
      0.0,
    -66.0,
], dtype=float)

# B bracket: B pivot to C pivot.
B_BRACKET_ZERO_TILT_DEG = +45.0
B_BRACKET_LEN = 77.7

B_BRACKET_SIZE = np.array([18.0, 18.0, B_BRACKET_LEN], dtype=float)

B_BRACKET_CENTER_FROM_B_LOCAL = np.array([
    0.0,
    0.0,
    -0.5 * B_BRACKET_LEN,
], dtype=float)

C_FROM_BRACKET_END_LOCAL = np.array([
    0.0,
    0.0,
    0.0,
], dtype=float)

# C-axis arm: C pivot to tool frame.
C_ARM_LEN = 43.5

C_ARM_SIZE = np.array([C_ARM_LEN, 18.0, 18.0], dtype=float)

C_ARM_CENTER_FROM_C_LOCAL = np.array([
    +0.5 * C_ARM_LEN,
    0.0,
    0.0,
], dtype=float)

TOOL_FROM_C_LOCAL = np.array([
    +C_ARM_LEN,
    0.0,
    0.0,
], dtype=float)

# Tool holder and nozzle tip.
# The -45 deg tool rotation cancels the B bracket's +45 deg zero tilt at B=C=0.
TOOL_ZERO_ROT_Y_DEG = -45.0

TOOL_HOLDER_SIZE = np.array([18.0, 18.0, 42.72], dtype=float)

TOOL_TIP_X_CAL_MM = +0.0

TOOL_HOLDER_CENTER_FROM_TOOL_LOCAL = np.array([
    TOOL_TIP_X_CAL_MM,
    0.0,
    0.0,
], dtype=float)

TIP_FROM_TOOL_HOLDER_CENTER_LOCAL = np.array([
    26.8,
    0.59,
    -47.8,
], dtype=float)


# ============================================================
# Cura base -> CL-data conversion
# ============================================================

# Cura coordinates of the object/bed center used to remap X/Y to X0 Y0.
CL_CURA_BED_CENTER_X_MM = 130.0
CL_CURA_BED_CENTER_Y_MM = 130.0

# Cura Z is shifted into the CL-data coordinate system.
CL_Z_OFFSET_MM = 5.0

# Vertical tool direction for the conventional 3-axis Cura base.
CL_BASE_TOOL_IJK = np.array([0.0, 0.0, 1.0], dtype=float)

# Cura parser settings.
CL_INCLUDE_TRAVEL_MOVES_FROM_CURA = False
CL_START_AFTER_LAYER_0 = True
CL_SKIP_TYPES = set()


# ============================================================
# Femoral mandrel and hemisphere geometry
# ============================================================

# Nominal physical sphere/hemisphere center used for the dome path.
CL_SPIRAL_SPHERE_CENTER_X_MM = 0.0
CL_SPIRAL_SPHERE_CENTER_Y_MM = 0.0
CL_SPIRAL_SPHERE_CENTER_Z_MM = 40.0

CL_SPIRAL_MANDREL_RADIUS_MM = 15.0

# Used only to draw the nominal base geometry in the CL-data preview.
CL_PREVIEW_CYLINDER_RADIUS_MM = 15.0
CL_PREVIEW_CYLINDER_HEIGHT_MM = CL_SPIRAL_SPHERE_CENTER_Z_MM

# Optional correction between the printed mandrel and the nominal model.
CL_SPIRAL_CENTER_X_CORRECTION_MM = 0
CL_SPIRAL_CENTER_Y_CORRECTION_MM = 0
CL_SPIRAL_CENTER_Z_CORRECTION_MM = 0

# Corrected sphere center actually used to generate the spiral.
CL_SPHERE_CENTER_X_MM = (
    CL_SPIRAL_SPHERE_CENTER_X_MM + CL_SPIRAL_CENTER_X_CORRECTION_MM
)
CL_SPHERE_CENTER_Y_MM = (
    CL_SPIRAL_SPHERE_CENTER_Y_MM + CL_SPIRAL_CENTER_Y_CORRECTION_MM
)
CL_SPHERE_CENTER_Z_MM = (
    CL_SPIRAL_SPHERE_CENTER_Z_MM + CL_SPIRAL_CENTER_Z_CORRECTION_MM
)


# ============================================================
# Non-planar hemisphere spiral
# ============================================================

CL_NUMBER_OF_SPIRAL_LAYERS = 2

# First printed dome radius = mandrel radius + clearance.
CL_FIRST_DOME_CLEARANCE_MM = 0.2

# Radial increment between subsequent dome layers.
CL_LAYER_HEIGHT_MM = 0.20

# Spacing between neighbouring spiral beads on the spherical surface.
CL_SPIRAL_LINE_SPACING_MM = 0.4

# Sampling distance along the generated spiral.
CL_POINT_SPACING_MM = 0.35

# Additional normal offset. Normally zero because radius already includes clearance.
CL_SURFACE_OFFSET_MM = 0.00

# Polar-angle range on the upper hemisphere.
CL_THETA_START_DEG = 3.0
CL_THETA_END_DEG = 90.0

# True: print from the dome top toward the equator.
CL_PRINT_TOP_TO_BOTTOM = True

# Angular seam shift applied to each subsequent dome layer.
CL_LAYER_PHASE_SHIFT_DEG = 180.0

# Tool direction follows the outward surface normal when +1.
CL_NORMAL_SIGN = 1.0

# Plotting decimation for spiral tool-direction vectors.
CL_VIZ_STEP = 200


# ============================================================
# Inter-layer travel and optional path placement
# ============================================================

# Insert lift -> XY reposition -> descend rows between dome layers.
CL_ADD_SAFE_REPOSITION_BETWEEN_LAYERS = True
CL_INTER_LAYER_Z_LIFT_MM = 5.0
CL_TRAVEL_IJK = np.array([0.0, 0.0, 1.0], dtype=float)

# Optional remapping of the generated spiral to the bed top.
CL_MAP_LOWEST_POINT_TO_BED_TOP = False
CL_Z_LIFT_MM = 0.0


# ============================================================
# IK solver
# ============================================================

# Convert commanded B/C angles to the physical/model rotation directions.
B_AXIS_SIGN = -1.0
C_AXIS_SIGN = -1.0

# Shared numerical solver tolerances/defaults.
IK_MAX_ITERS = 1000
IK_TOL_POS_MM = 0.02
IK_TOL_DIR = 0.01
IK_MU = 0.1

# Finite-difference steps for the numerical B/C Jacobian.
IK_FD_EPS_C_RAD = 1e-4
IK_FD_EPS_B_RAD = 1e-4

# Preferred C branch for the dome path.
IK_PREFERRED_C_SIGN = -1.0
IK_C_MIN_RAD = -np.pi
IK_C_MAX_RAD = 0.0

# Penalty and branch score for positive C.
IK_C_POSITIVE_PENALTY_LAMBDA = 1e-3
IK_C_POSITIVE_PENALTY_THRESHOLD_RAD = 0.0
IK_C_PREFERRED_BRANCH_SCORE = 20.0

# Numerical branch seeding and branch scoring.
IK_BC_BRANCH_NUDGE_C_RAD = 1.0
IK_BC_BRANCH_NUDGE_B_RAD = 1.0

IK_BC_BRANCH_SCORE_DIR = 1.0
IK_BC_BRANCH_SCORE_CONTINUITY = 0.1
IK_BC_BRANCH_SCORE_POSITIVE_C = 5.0


# ============================================================
# Visualizer geometry
# ============================================================

# Shared visualizer geometry.
VIZ_AXIS_RADIUS = 2.5
VIZ_AXIS_B_LEN = 150.0
VIZ_AXIS_C_LEN = 120.0
VIZ_TIP_SPHERE_RADIUS = 2.5

CAMERA_POSITION = [
    (-700.0, -1300.0, 900.0),
    (0.0, 0.0, 250.0),
    (0.0, 0.0, 1.0),
]


# ============================================================
# IK-to-G-code conversion
# ============================================================

GCODE_BASENAME = "04_femoral_joint_5axis_print"
GCODE_EXT = ".gcode"

# Solved IK X/Y are centered around (0, 0); machine coordinates use 0..150 mm.
GCODE_X_CENTER_OFFSET_MM = 75.0
GCODE_Y_CENTER_OFFSET_MM = 75.0

# Map solved z_table to machine Z.
GCODE_ZTABLE_TO_MACHINE_Z_OFFSET = 5.0
GCODE_ZTABLE_SIGN = 1.0

# IK stores B/C in radians; Klipper commands use degrees.
GCODE_ANGLES_IN_RADIANS = True
GCODE_OUTPUT_BC_IN_DEGREES = True

# Optional machine zero offsets in output angle units.
GCODE_B_OFFSET = 0.0
GCODE_C_OFFSET = 0.0


# ============================================================
# G-code machine limits
# ============================================================

GCODE_X_MIN_MM = 0.0
GCODE_X_MAX_MM = 150.0

GCODE_Y_MIN_MM = 0.0
GCODE_Y_MAX_MM = 150.0

GCODE_Z_MIN_MM = -20.0
GCODE_Z_MAX_MM = 332.8

GCODE_C_MIN_DEG = -190.0
GCODE_C_MAX_DEG = 90.0

# B is intentionally not range-checked in the current machine configuration.
GCODE_CHECK_B_RANGE = False
GCODE_B_MIN_DEG = -1e9
GCODE_B_MAX_DEG = +1e9


# ============================================================
# G-code print settings
# ============================================================

GCODE_DRY_RUN = False

GCODE_BED_TEMP_C = 55.0
GCODE_FILAMENT_1_NOZZLE_TEMP_C = 230.0
GCODE_FILAMENT_2_NOZZLE_TEMP_C = 230.0
GCODE_WAIT_FOR_FILAMENT_2_TEMP_BEFORE_PAUSE = True

# Optional filament change between the Cura base and the dome path.
GCODE_ENABLE_COLOR_CHANGE_AT_SPIRAL = True
GCODE_COLOR_CHANGE_COMMAND = "COLOR_CHANGE"
GCODE_RETRACT_BEFORE_COLOR_CHANGE_MM = 1.0
GCODE_REPRIME_AFTER_COLOR_CHANGE_MM = 3.0

GCODE_BASE_PRINT_SPEED_MM_S = 10.0
GCODE_SPIRAL_PRINT_SPEED_MM_S = 8.0
GCODE_TRAVEL_SPEED_MM_S = 40.0

GCODE_PRIME_EXTRUSION_MM = 15.0
GCODE_EXTRUSION_RELATIVE = True

# Extrusion model used by the G-code converter.
GCODE_LINE_WIDTH_MM = 0.45
GCODE_LAYER_HEIGHT_MM = 0.20
GCODE_FILAMENT_DIAMETER_MM = 1.75

GCODE_FLOW_MULTIPLIER_BASE = 1.4
GCODE_FLOW_MULTIPLIER_SPIRAL = 1.5

# Output formatting.
GCODE_DECIMALS_POS = 4
GCODE_DECIMALS_E = 5
GCODE_DECIMALS_ANGLE = 4


# ============================================================
# Derived home geometry
# ============================================================

def compute_home_bed_center_z0() -> float:
    """
    Compute the bed-center world Z coordinate for z_table=0.

    At the zero pose (X=Y=z_table=B=C=0), the nozzle tip is assumed to touch
    the bed top. The calculation mirrors the explicit head-frame geometry used
    by the IK solvers and visualizer.
    """
    carriage_center_z0 = GANTRY_Z - 0.5 * CARRIAGE_SIZE[2]
    p_Baxis_z0 = carriage_center_z0 + B_PIVOT_FROM_CARRIAGE_CENTER[2]

    def Ry_deg(a_deg):
        a = np.deg2rad(a_deg)
        ca, sa = np.cos(a), np.sin(a)
        return np.array([
            [ ca, 0.0, sa],
            [0.0, 1.0, 0.0],
            [-sa, 0.0, ca],
        ], dtype=float)

    R_B = Ry_deg(B_BRACKET_ZERO_TILT_DEG)

    p_b_bracket = (
        np.array([0.0, 0.0, p_Baxis_z0], dtype=float)
        + R_B @ B_BRACKET_CENTER_FROM_B_LOCAL
    )

    p_bracket_end = (
        p_b_bracket
        + R_B @ np.array([0.0, 0.0, -0.5 * B_BRACKET_LEN], dtype=float)
    )

    p_Caxis = p_bracket_end + R_B @ C_FROM_BRACKET_END_LOCAL
    p_tool = p_Caxis + R_B @ TOOL_FROM_C_LOCAL

    R_tool = R_B @ Ry_deg(TOOL_ZERO_ROT_Y_DEG)

    p_tool_holder = p_tool + R_tool @ TOOL_HOLDER_CENTER_FROM_TOOL_LOCAL
    p_tip = p_tool_holder + R_tool @ TIP_FROM_TOOL_HOLDER_CENTER_LOCAL

    bed_top_z0 = p_tip[2]
    bed_center_z0 = bed_top_z0 - 0.5 * BED_SIZE[2]

    return float(bed_center_z0)


BED_CENTER_Z0 = compute_home_bed_center_z0()
