# -*- coding: utf-8 -*-
"""
S04_femoral_joint_gcode_generator.py

Converts the solved femoral-joint path to Klipper-compatible five-axis G-code.

The mandrel and dome sections use separate print speeds and flow multipliers.
The no-extrusion index file marks safe inter-layer reposition moves. An
optional filament change can be inserted at the mandrel-to-dome transition.

All print settings, coordinate transforms and machine limits are read from
S00_femoral_joint_parameters.py.
"""
from __future__ import annotations

import math
import re
from pathlib import Path

import numpy as np
import S00_femoral_joint_parameters as P


# ============================================================
# Files
# ============================================================

BASE_DIR = Path(P.BASE_DIR)

IK_PATH = Path(P.SOLVED_IK_PATH)
CL_PATH = Path(P.CLDATA_PATH)

# Used to locate the mandrel-to-dome transition.
CURA_BASE_CLDATA_PATH = Path(P.CURA_BASE_CLDATA_PATH)

# Combined travel-row indices generated by S01.
NO_EXTRUDE_INDEX_PATH = Path(P.COMBINED_NO_EXTRUDE_INDICES_PATH)

GCODE_BASENAME = str(P.GCODE_BASENAME)
GCODE_EXT = str(P.GCODE_EXT)


# ============================================================
# Temperatures
# ============================================================

DRY_RUN = bool(P.GCODE_DRY_RUN)

BED_TEMP_C = float(P.GCODE_BED_TEMP_C)

FILAMENT_1_NOZZLE_TEMP_C = float(P.GCODE_FILAMENT_1_NOZZLE_TEMP_C)
FILAMENT_2_NOZZLE_TEMP_C = float(P.GCODE_FILAMENT_2_NOZZLE_TEMP_C)

WAIT_FOR_FILAMENT_2_TEMP_BEFORE_PAUSE = bool(
    P.GCODE_WAIT_FOR_FILAMENT_2_TEMP_BEFORE_PAUSE
)


# ============================================================
# Filament change
# ============================================================

ENABLE_COLOR_CHANGE_AT_SPIRAL = bool(P.GCODE_ENABLE_COLOR_CHANGE_AT_SPIRAL)
COLOR_CHANGE_COMMAND = str(P.GCODE_COLOR_CHANGE_COMMAND)

RETRACT_BEFORE_COLOR_CHANGE_MM = float(P.GCODE_RETRACT_BEFORE_COLOR_CHANGE_MM)
REPRIME_AFTER_COLOR_CHANGE_MM = float(P.GCODE_REPRIME_AFTER_COLOR_CHANGE_MM)


# ============================================================
# Speeds
# ============================================================

BASE_PRINT_SPEED_MM_S = float(P.GCODE_BASE_PRINT_SPEED_MM_S)
SPIRAL_PRINT_SPEED_MM_S = float(P.GCODE_SPIRAL_PRINT_SPEED_MM_S)
TRAVEL_SPEED_MM_S = float(P.GCODE_TRAVEL_SPEED_MM_S)

PRIME_EXTRUSION_MM = float(P.GCODE_PRIME_EXTRUSION_MM)

EXTRUSION_RELATIVE = bool(P.GCODE_EXTRUSION_RELATIVE)


# ============================================================
# Extrusion
# ============================================================

LINE_WIDTH_MM = float(P.GCODE_LINE_WIDTH_MM)
LAYER_HEIGHT_MM = float(P.GCODE_LAYER_HEIGHT_MM)
FILAMENT_DIAMETER_MM = float(P.GCODE_FILAMENT_DIAMETER_MM)

FLOW_MULTIPLIER_BASE = float(P.GCODE_FLOW_MULTIPLIER_BASE)
FLOW_MULTIPLIER_SPIRAL = float(P.GCODE_FLOW_MULTIPLIER_SPIRAL)


# ============================================================
# Output formatting
# ============================================================

DECIMALS_POS = int(P.GCODE_DECIMALS_POS)
DECIMALS_E = int(P.GCODE_DECIMALS_E)
DECIMALS_ANGLE = int(P.GCODE_DECIMALS_ANGLE)


# ============================================================
# Machine coordinate mapping
# ============================================================

X_CENTER_OFFSET_MM = float(P.GCODE_X_CENTER_OFFSET_MM)
Y_CENTER_OFFSET_MM = float(P.GCODE_Y_CENTER_OFFSET_MM)

ZTABLE_TO_MACHINE_Z_OFFSET = float(P.GCODE_ZTABLE_TO_MACHINE_Z_OFFSET)
ZTABLE_SIGN = float(P.GCODE_ZTABLE_SIGN)

ANGLES_IN_RADIANS = bool(P.GCODE_ANGLES_IN_RADIANS)
OUTPUT_BC_IN_DEGREES = bool(P.GCODE_OUTPUT_BC_IN_DEGREES)

B_OFFSET = float(P.GCODE_B_OFFSET)
C_OFFSET = float(P.GCODE_C_OFFSET)


# ============================================================
# Machine limits
# ============================================================

X_MIN_MM = float(P.GCODE_X_MIN_MM)
X_MAX_MM = float(P.GCODE_X_MAX_MM)

Y_MIN_MM = float(P.GCODE_Y_MIN_MM)
Y_MAX_MM = float(P.GCODE_Y_MAX_MM)

Z_MIN_MM = float(P.GCODE_Z_MIN_MM)
Z_MAX_MM = float(P.GCODE_Z_MAX_MM)

C_MIN_DEG = float(P.GCODE_C_MIN_DEG)
C_MAX_DEG = float(P.GCODE_C_MAX_DEG)

CHECK_B_RANGE = bool(P.GCODE_CHECK_B_RANGE)
B_MIN_DEG = float(P.GCODE_B_MIN_DEG)
B_MAX_DEG = float(P.GCODE_B_MAX_DEG)


# ============================================================
# Helpers
# ============================================================

def load_numeric_file(path: Path, min_cols: int) -> np.ndarray:
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"File not found:\n{path}")

    data = np.loadtxt(path, comments="#")

    if data.ndim == 1:
        data = data.reshape(1, -1)

    if data.ndim != 2 or data.shape[1] < min_cols:
        raise ValueError(f"{path.name} must have at least {min_cols} columns")

    return data


def load_no_extrude_indices(path: Path) -> set[int]:
    """Load destination-row indices for travel moves without extrusion."""
    path = Path(path)

    if not path.exists():
        print(f"Warning: no travel-index file found: {path}")
        print("Inter-layer reposition moves will be treated as printing moves.")
        return set()

    indices: set[int] = set()

    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for raw in f:
            line = raw.strip()

            if not line or line.startswith("#"):
                continue

            try:
                indices.add(int(line))
            except ValueError:
                raise ValueError(
                    f"Invalid no-extrude index line in {path.name}: {line!r}"
                )

    return indices


def bead_area_mm2(line_width: float, layer_height: float) -> float:
    return line_width * layer_height


def filament_area_mm2(filament_diameter: float) -> float:
    r = 0.5 * filament_diameter
    return math.pi * r * r


def extrusion_per_mm(
    line_width: float,
    layer_height: float,
    filament_diameter: float,
    flow_multiplier: float = 1.0,
) -> float:
    return (
        flow_multiplier
        * bead_area_mm2(line_width, layer_height)
        / filament_area_mm2(filament_diameter)
    )


def fmt(v: float, n: int) -> str:
    return f"{v:.{n}f}"


def transform_x(x_centered: float) -> float:
    return X_CENTER_OFFSET_MM + x_centered


def transform_y(y_centered: float) -> float:
    return Y_CENTER_OFFSET_MM + y_centered


def transform_z(z_table: float) -> float:
    return ZTABLE_TO_MACHINE_Z_OFFSET + ZTABLE_SIGN * z_table


def transform_angle(a: float, offset: float = 0.0) -> float:
    if ANGLES_IN_RADIANS and OUTPUT_BC_IN_DEGREES:
        return math.degrees(a) + offset

    return a + offset


def segment_lengths_from_cl_xyz(cl_xyz: np.ndarray) -> np.ndarray:
    d = np.diff(cl_xyz, axis=0)
    return np.linalg.norm(d, axis=1)


def validate_move(x: float, y: float, z: float, b: float, c: float) -> None:
    if not (X_MIN_MM <= x <= X_MAX_MM):
        raise ValueError(f"X out of range: {x:.4f} mm")

    if not (Y_MIN_MM <= y <= Y_MAX_MM):
        raise ValueError(f"Y out of range: {y:.4f} mm")

    if not (Z_MIN_MM <= z <= Z_MAX_MM):
        raise ValueError(f"Z out of range: {z:.4f} mm")

    if not (C_MIN_DEG <= c <= C_MAX_DEG):
        raise ValueError(f"C out of range: {c:.4f} deg")

    if CHECK_B_RANGE and not (B_MIN_DEG <= b <= B_MAX_DEG):
        raise ValueError(f"B out of range: {b:.4f} deg")


def next_indexed_output_path(base_dir: Path, basename: str, ext: str) -> Path:
    base_dir = Path(base_dir)

    pattern = re.compile(rf"^{re.escape(basename)}_(\d+){re.escape(ext)}$")
    max_index = 0

    for p in base_dir.iterdir():
        if not p.is_file():
            continue

        match = pattern.match(p.name)

        if match:
            max_index = max(max_index, int(match.group(1)))

    return base_dir / f"{basename}_{max_index + 1}{ext}"


def transformed_row(ik_row: np.ndarray) -> tuple[float, float, float, float, float]:
    """
    Converts one IK row:
        x y z_table B C

    to machine G-code axes:
        X Y Z B C
    """
    x = transform_x(float(ik_row[0]))
    y = transform_y(float(ik_row[1]))
    z = transform_z(float(ik_row[2]))

    b = transform_angle(float(ik_row[3]), B_OFFSET)
    c = transform_angle(float(ik_row[4]), C_OFFSET)

    validate_move(x, y, z, b, c)

    return x, y, z, b, c


def g1_xyzbc(
    x: float,
    y: float,
    z: float,
    b: float,
    c: float,
    feed: float,
    e: float | None = None,
) -> str:
    if e is None:
        return (
            "G1 "
            f"X{fmt(x, DECIMALS_POS)} "
            f"Y{fmt(y, DECIMALS_POS)} "
            f"Z{fmt(z, DECIMALS_POS)} "
            f"B{fmt(b, DECIMALS_ANGLE)} "
            f"C{fmt(c, DECIMALS_ANGLE)} "
            f"F{fmt(feed, 0)}"
        )

    return (
        "G1 "
        f"X{fmt(x, DECIMALS_POS)} "
        f"Y{fmt(y, DECIMALS_POS)} "
        f"Z{fmt(z, DECIMALS_POS)} "
        f"B{fmt(b, DECIMALS_ANGLE)} "
        f"C{fmt(c, DECIMALS_ANGLE)} "
        f"E{fmt(e, DECIMALS_E)} "
        f"F{fmt(feed, 0)}"
    )


def extrusion_line(e_value: float, feed: float = 300.0) -> str:
    return f"G1 E{fmt(e_value, DECIMALS_E)} F{fmt(feed, 0)}"


# ============================================================
# Main
# ============================================================

def main() -> None:
    ik = load_numeric_file(IK_PATH, min_cols=5)                 # x y z_table B C
    cl = load_numeric_file(CL_PATH, min_cols=6)                 # x y z i j k
    cura_base_cl = load_numeric_file(CURA_BASE_CLDATA_PATH, min_cols=6)

    spiral_start_index = len(cura_base_cl)

    # These indices are already GLOBAL combined row indices.
    no_extrude_global_indices = load_no_extrude_indices(NO_EXTRUDE_INDEX_PATH)

    if len(ik) != len(cl):
        raise ValueError(
            f"Row count mismatch: IK has {len(ik)} rows, CL has {len(cl)} rows. "
            "Use matching files from the same solve."
        )

    if not (0 < spiral_start_index < len(cl)):
        raise ValueError(
            f"Invalid spiral_start_index = {spiral_start_index}. "
            f"Combined CL has {len(cl)} rows."
        )

    for idx in sorted(no_extrude_global_indices):
        if idx <= spiral_start_index or idx >= len(cl):
            raise ValueError(
                f"No-extrude global row index {idx} is outside the spiral region. "
                f"spiral_start_index={spiral_start_index}, total rows={len(cl)}"
            )

    e_per_mm_base = extrusion_per_mm(
        line_width=LINE_WIDTH_MM,
        layer_height=LAYER_HEIGHT_MM,
        filament_diameter=FILAMENT_DIAMETER_MM,
        flow_multiplier=FLOW_MULTIPLIER_BASE,
    )

    e_per_mm_spiral = extrusion_per_mm(
        line_width=LINE_WIDTH_MM,
        layer_height=LAYER_HEIGHT_MM,
        filament_diameter=FILAMENT_DIAMETER_MM,
        flow_multiplier=FLOW_MULTIPLIER_SPIRAL,
    )

    cl_xyz = cl[:, :3]
    seg_len = segment_lengths_from_cl_xyz(cl_xyz)

    feed_print_base = BASE_PRINT_SPEED_MM_S * 60.0
    feed_print_spiral = SPIRAL_PRINT_SPEED_MM_S * 60.0
    feed_travel = TRAVEL_SPEED_MM_S * 60.0

    lines: list[str] = []

    # --------------------------------------------------------
    # Header / startup
    # --------------------------------------------------------
    lines.append("; 5-axis generated G-code")
    lines.append("; Combined Cura base + two-layer hemisphere spiral")
    lines.append("; Parameters source: S00_femoral_joint_parameters.py")
    lines.append(f"; Source IK: {IK_PATH.name}")
    lines.append(f"; Source CL: {CL_PATH.name}")
    lines.append(f"; Cura base CL: {CURA_BASE_CLDATA_PATH.name}")
    lines.append(f"; Combined no-extrude index file: {NO_EXTRUDE_INDEX_PATH.name}")
    lines.append(f"; Spiral starts at row index: {spiral_start_index}")
    lines.append(f"; No-extrude global row indices: {sorted(no_extrude_global_indices)}")
    lines.append(f"; DRY_RUN = {DRY_RUN}")
    lines.append(f"; Filament 1 nozzle temp: {FILAMENT_1_NOZZLE_TEMP_C:.1f} C")
    lines.append(f"; Filament 2 nozzle temp: {FILAMENT_2_NOZZLE_TEMP_C:.1f} C")
    lines.append(f"; Bed temp: {BED_TEMP_C:.1f} C")

    if not DRY_RUN:
        lines.append(f"; e_per_mm_base = {e_per_mm_base:.6f}")
        lines.append(f"; e_per_mm_spiral = {e_per_mm_spiral:.6f}")

    lines.append("")

    lines.append("G21                     ; mm units")
    lines.append("G90                     ; absolute XYZBC")

    if not DRY_RUN and EXTRUSION_RELATIVE:
        lines.append("M83                     ; relative extrusion")

    if not DRY_RUN:
        lines.append(f"M140 S{fmt(BED_TEMP_C, 1)}        ; set bed temp")
        lines.append(f"M104 S{fmt(FILAMENT_1_NOZZLE_TEMP_C, 1)} ; set nozzle temp for filament 1")

    lines.append("HOME_ALL")

    if not DRY_RUN:
        lines.append(f"M190 S{fmt(BED_TEMP_C, 1)}        ; wait for bed temp")
        lines.append(f"M109 S{fmt(FILAMENT_1_NOZZLE_TEMP_C, 1)} ; wait for filament 1 nozzle temp")
        lines.append("G92 E0")

    lines.append("")

    # --------------------------------------------------------
    # First move: go to start point without extrusion
    # --------------------------------------------------------
    x0, y0, z0, b0, c0 = transformed_row(ik[0])

    lines.append("; Move to first Cura base point")
    lines.append(g1_xyzbc(x0, y0, z0, b0, c0, feed_travel))

    if not DRY_RUN:
        lines.append("; Prime filament 1")
        lines.append(extrusion_line(PRIME_EXTRUSION_MM, feed=300.0))

    lines.append("")

    # --------------------------------------------------------
    # Main moves
    # --------------------------------------------------------
    for row_idx in range(1, len(ik)):
        x, y, z, b, c = transformed_row(ik[row_idx])

        # ----------------------------------------------------
        # Transition from Cura base to first dome spiral
        # ----------------------------------------------------
        if row_idx == spiral_start_index:
            lines.append("")
            lines.append("; ==================================================")
            lines.append("; Transition from Cura base to first 5-axis dome spiral")
            lines.append("; Sequence:")
            lines.append(";   1) retract")
            lines.append(";   2) set/wait filament 2 temp")
            lines.append(";   3) COLOR_CHANGE macro lifts Z and pauses")
            lines.append(";   4) user switches filament")
            lines.append(";   5) resume")
            lines.append(";   6) move to first dome start without extrusion")
            lines.append(";   7) reprime")
            lines.append("; ==================================================")

            if not DRY_RUN:
                lines.append("; Retract filament 1 before colour change")
                lines.append(extrusion_line(-RETRACT_BEFORE_COLOR_CHANGE_MM, feed=300.0))

                lines.append(f"; Set nozzle temp for filament 2: {FILAMENT_2_NOZZLE_TEMP_C:.1f} C")

                if WAIT_FOR_FILAMENT_2_TEMP_BEFORE_PAUSE:
                    lines.append(
                        f"M109 S{fmt(FILAMENT_2_NOZZLE_TEMP_C, 1)} "
                        "; wait for filament 2 nozzle temp"
                    )
                else:
                    lines.append(
                        f"M104 S{fmt(FILAMENT_2_NOZZLE_TEMP_C, 1)} "
                        "; set filament 2 nozzle temp, no wait"
                    )

            if ENABLE_COLOR_CHANGE_AT_SPIRAL:
                lines.append(f"{COLOR_CHANGE_COMMAND} ; manual filament colour change")
            else:
                lines.append("; Colour change disabled")

            lines.append("; Re-assert modes after resume")
            lines.append("G90 ; absolute XYZBC")

            if not DRY_RUN and EXTRUSION_RELATIVE:
                lines.append("M83 ; relative extrusion")

            lines.append("; Move to first dome start without extrusion")
            lines.append(g1_xyzbc(x, y, z, b, c, feed_travel))

            if not DRY_RUN:
                lines.append("; Re-prime filament 2 before starting first dome")
                lines.append(extrusion_line(REPRIME_AFTER_COLOR_CHANGE_MM, feed=300.0))
                lines.append("G92 E0")

            lines.append("; Start first dome spiral")
            lines.append("")
            continue

        # ----------------------------------------------------
        # No-extrude reposition moves inside the spiral section
        # Example:
        #   first dome finished
        #   move up in Z
        #   move XY toward second dome start
        #   move down to second dome start Z
        # ----------------------------------------------------
        if row_idx in no_extrude_global_indices:
            lines.append("")
            lines.append(f"; No-extrude inter-dome reposition move at combined row {row_idx}")
            lines.append(g1_xyzbc(x, y, z, b, c, feed_travel))
            continue

        # ----------------------------------------------------
        # Normal print move
        # ----------------------------------------------------
        if row_idx < spiral_start_index:
            feed_print = feed_print_base
            e_per_mm = e_per_mm_base
        else:
            feed_print = feed_print_spiral
            e_per_mm = e_per_mm_spiral

        if DRY_RUN:
            lines.append(g1_xyzbc(x, y, z, b, c, feed_print))
        else:
            e = seg_len[row_idx - 1] * e_per_mm
            lines.append(g1_xyzbc(x, y, z, b, c, feed_print, e=e))

    # --------------------------------------------------------
    # End
    # --------------------------------------------------------
    lines.append("")
    lines.append("; End")

    if not DRY_RUN:
        lines.append("G92 E0")
        lines.append("G1 E-1.00000 F300")
        lines.append("M104 S0")
        lines.append("M140 S0")

    z_end_current = transform_z(float(ik[-1, 2]))
    z_safe = min(max(z_end_current + 10.0, Z_MIN_MM), Z_MAX_MM)

    lines.append(f"G1 Z{fmt(z_safe, DECIMALS_POS)} F{fmt(feed_travel, 0)}")
    lines.append("M84")

    gcode_path = next_indexed_output_path(BASE_DIR, GCODE_BASENAME, GCODE_EXT)
    gcode_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {gcode_path}")
    print(
        f"Rows: {len(cl)} total, {spiral_start_index} mandrel, "
        f"{len(cl) - spiral_start_index} dome"
    )
    print(f"Travel rows: {sorted(no_extrude_global_indices)}")
    if not DRY_RUN:
        print(
            f"Extrusion per mm: mandrel {e_per_mm_base:.6f}, "
            f"dome {e_per_mm_spiral:.6f}"
        )



if __name__ == "__main__":
    main()